repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the latest version from https://github.com/pre-commit/pre-commit-hooks
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.0  # Use the latest version from https://github.com/pycqa/flake8
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
        args: [--docstring-convention=google]
-   repo: local
    hooks:
    -   id: pytest
        name: Run tests, write a report in TESTS, and update README
        entry: python testscoverage.py
        language: python
        pass_filenames: false
